# Generated by Django 5.2.9 on 2026-01-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
