# Generated by Django 5.2.9 on 2026-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="icon_image",
            field=models.ImageField(blank=True, null=True, upload_to="task_icons/"),
        ),
    ]
